// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.learning;

public final class EmployeeOuterClass {
  private EmployeeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_learning_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_learning_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_learning_EmployeeRespnse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_learning_EmployeeRespnse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Employee.proto\022\014com.learning\"N\n\010Employ" +
      "ee\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\023\n\013dateOfB" +
      "irth\030\003 \001(\t\022\022\n\ndepartment\030\004 \001(\t\"\"\n\017Employ" +
      "eeRespnse\022\017\n\007message\030\001 \001(\t2W\n\017EmployeeSe" +
      "rvice\022D\n\013getEmployee\022\026.com.learning.Empl" +
      "oyee\032\035.com.learning.EmployeeRespnseB\002P\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_learning_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_learning_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_learning_Employee_descriptor,
        new java.lang.String[] { "Name", "Age", "DateOfBirth", "Department", });
    internal_static_com_learning_EmployeeRespnse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_learning_EmployeeRespnse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_learning_EmployeeRespnse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
