// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.learning;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.learning.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>string dateOfBirth = 3;</code>
   */
  java.lang.String getDateOfBirth();
  /**
   * <code>string dateOfBirth = 3;</code>
   */
  com.google.protobuf.ByteString
      getDateOfBirthBytes();

  /**
   * <code>string department = 4;</code>
   */
  java.lang.String getDepartment();
  /**
   * <code>string department = 4;</code>
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();
}
