// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.learning;

public interface EmployeeRespnseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.learning.EmployeeRespnse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
